# ==========================================
# EVALUTY BACKEND - Configuración principal
# ==========================================

spring.application.name=evaluty-backend
server.port=8080

# --- MongoDB ---
spring.data.mongodb.uri=mongodb://localhost:27017/evaluty_db
spring.data.mongodb.database=evaluty_db

# --- JWT ---
evaluty.jwt.secret=TuClaveSecretaSuperLargaParaJWT_CambiaEstoEnProduccion_MinimoTreintaYDosCaracteres
evaluty.jwt.expiration=86400000

# --- Python ---
# Ruta relativa al main.py desde la carpeta backend/
# main.py es el orquestador que llama internamente a catastro.py, bot_inmobiliario.py, calculo.py y generador_pdf.py
evaluty.python.executable=C:/Users/mogur/Desktop/Apuntes UNIR/DAW/Segundo Curso DAW/10.-TFG/TFG-Evaluador-Precios-Viviendas/data-service/venv/Scripts/python.exe
evaluty.python.main-path=../data-service/main.py

# Tiempo máximo de espera para el scraping (2 minutos)
spring.mvc.async.request-timeout=120000

# --- CORS (Angular en dev) ---
evaluty.cors.allowed-origins=http://localhost:4200

# --- Logging ---
logging.level.com.evaluty=DEBUG
